"""Renaming field in Notification model

Revision ID: 88c02e77fad7
Revises: 888f1110030d
Create Date: 2026-02-03 14:12:45.641528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88c02e77fad7'
down_revision: Union[str, Sequence[str], None] = '888f1110030d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startup_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('startup_time')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startup_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_column('startup_at')

    # ### end Alembic commands ###
