"""Added a user to a notification

Revision ID: 667d6e1878e8
Revises: 17758377e421
Create Date: 2026-02-02 16:38:02.862454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667d6e1878e8'
down_revision: Union[str, Sequence[str], None] = '17758377e421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('startup_time', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_notification_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notification_user_id_user'), type_='foreignkey')
        batch_op.drop_column('startup_time')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
