"""Added support table for observing notification delivery

Revision ID: 911e4dd6d2bf
Revises: 92a33de0e968
Create Date: 2026-03-10 00:33:07.539246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '911e4dd6d2bf'
down_revision: Union[str, Sequence[str], None] = '92a33de0e968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notification', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_schedule_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('next_fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery')),
    sa.UniqueConstraint('notification_schedule_id', 'next_fire_at', name='uq_notification_delivery_notification_schedule_id_next_fire_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_delivery')
    # ### end Alembic commands ###
