"""The table "notification_schedule", renaming field

Revision ID: 92a33de0e968
Revises: d8e93a4d46d0
Create Date: 2026-03-10 00:20:14.910122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92a33de0e968'
down_revision: Union[str, Sequence[str], None] = 'd8e93a4d46d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'notification_schedule',  # Table name
        'fire_at',  # Old column name
        new_column_name='next_fire_at',  # New column name
        existing_type=sa.DateTime(timezone=True),  # Must specify the existing type
        # You may also need existing_nullable or existing_server_default
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'notification_schedule',  # Table name
        'next_fire_at',  # Old column name
        new_column_name='fire_at',  # New column name
        existing_type=sa.DateTime(timezone=True),  # Must specify the existing type
        # You may also need existing_nullable or existing_server_default
    )

    # ### end Alembic commands ###
