"""Added status to NotificationSchedule

Revision ID: a15f746f6399
Revises: 92a33de0e968
Create Date: 2026-03-16 19:27:48.190078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15f746f6399'
down_revision: Union[str, Sequence[str], None] = '92a33de0e968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_schedule', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
