"""Added model for Notification Schedule

Revision ID: d8e93a4d46d0
Revises: 29e9326452c2
Create Date: 2026-03-03 00:07:46.433793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8e93a4d46d0'
down_revision: Union[str, Sequence[str], None] = '29e9326452c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat_settings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_notification_schedule_channel_id_channel')),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name=op.f('fk_notification_schedule_notification_id_notification')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_schedule'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_schedule')
    # ### end Alembic commands ###
