"""Added status to NotificationSchedule

Revision ID: f618684a7f45
Revises: 911e4dd6d2bf
Create Date: 2026-03-11 21:39:14.542069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f618684a7f45'
down_revision: Union[str, Sequence[str], None] = '911e4dd6d2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_schedule', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
